### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by alovegren** [alovegren/mini-plant-picker#1]
- [x] layout
- [x]  index route
- [ ] find some data sets/sources
- [ ] i/o

**Comment by andrewdmoore408** [comment]
I wanted to see how reactions would appear here haha.

Do you want to take a crack at finding data sets/possible APIs, and I'll get started on the basic file setup, layout draft, and index route?

Where do you want to start with I/O? We could start with the index route rendering a home page and returning 200, does that work?

Should I add sessions as well?

**Comment by alovegren** [comment]
I'm closing this issue because it's too vague but I'm terribly sorry I never replied to this comment. I think we're past your first two questions, but I have no idea if we should add sessions at this point.....................
